default_context:
  project_name: 'simple-chatbot-rpp'
  project_slug: 'simple-chatbot-rpp'
  domain_main: 'simple-chatbot-rpp.com'
  domain_staging: 'stag.simple-chatbot-rpp.com'
  docker_swarm_stack_name_main: 'simple-chatbot-rpp-com'
  docker_swarm_stack_name_staging: 'stag-simple-chatbot-rpp-com'
  secret_key: 'c807db312151bfd51a27d00874f00419f75f430b8cb254d6d3cb461be2da41a8'
  first_superuser: 'admin@simple-chatbot-rpp.com'
  first_superuser_password: 'admin123'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.simple-chatbot-rpp.com", "https://stag.simple-chatbot-rpp.com", "https://simple-chatbot-rpp.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@simple-chatbot-rpp.com'
  postgres_password: 'changethis'
  pgadmin_default_user: 'admin@simple-chatbot-rpp.com'
  pgadmin_default_user_password: 'admin123'
  traefik_constraint_tag: 'simple-chatbot-rpp.com'
  traefik_constraint_tag_staging: 'stag.simple-chatbot-rpp.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:admin123'
  sentry_dsn: ''
  docker_image_prefix: 'rpp-'
  docker_image_backend: 'rpp-backend'
  docker_image_celeryworker: 'rpp-celeryworker'
  docker_image_frontend: 'rpp-frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
